In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv("../enrich/movies.csv")
ratings = pd.read_csv("../enrich/ratings.csv")

In [3]:
movies

,movieid,title,genres
0,0,Toy Story (1995),Animation|Children's|Comedy
1,1,Jumanji (1995),Adventure|Children's|Fantasy
2,2,Grumpier Old Men (1995),Comedy|Romance
3,3,Waiting to Exhale (1995),Comedy|Drama
4,4,Father of the Bride Part II (1995),Comedy
...,...,...,...
3878,3878,Meet the Parents (2000),Comedy
3879,3879,Requiem for a Dream (2000),Drama
3880,3880,Tigerland (2000),Drama
3881,3881,Two Family House (2000),Drama
3882,3882,"Contender, The (2000)",Drama|Thriller

In [4]:
# ratings.sort_values(by = "userid").to_csv("../enrich/ratings.csv", index=False)
ratings

,userid,movieid,rating,timestamp,title,genres
0,1,1176,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama
1,1,47,5,978824351,Pocahontas (1995),Animation|Children's|Musical|Romance
2,1,926,4,978301752,Gigi (1958),Musical
3,1,1189,4,978300719,To Kill a Mockingbird (1962),Drama
4,1,1672,4,978300055,Titanic (1997),Drama|Romance
...,...,...,...,...,...,...
1000204,6040,2572,2,956716343,Superman II (1980),Action|Adventure|Sci-Fi
1000205,6040,1878,4,997454036,West Side Story (1961),Musical|Romance
1000206,6040,892,4,956716845,Rear Window (1954),Mystery|Thriller
1000207,6040,2595,4,957717463,Invasion of the Body Snatchers (1956),Horror|Sci-Fi
1000208,6040,1157,2,956716317,"Cook the Thief His Wife & Her Lover, The (1989)",Drama

In [11]:
for x in ratings.groupby("userid").groups:
    print(ratings.groupby("userid").get_group(1))
    break

    userid  movieid  rating  timestamp  \
0        1     1176       5  978300760
1        1       47       5  978824351
2        1      926       4  978301752
3        1     1189       4  978300719
4        1     1672       4  978300055
5        1     2693       4  978302091
6        1     2618       3  978824268
7        1     2623       4  978301570
8        1      711       3  978300760
9        1      735       3  978824268
10       1      591       5  978824268
11       1     1892       5  978301590
12       1      523       5  978824195
13       1     1081       4  978301953
14       1     2735       5  978300719
15       1     1949       4  978301777
16       1      604       4  978301398
17       1     1893       4  978301753
18       1     1267       5  978302039
19       1      584       4  978824268
20       1     1226       4  978302091
21       1      902       3  978301968
22       1     1179       3  978302268
23       1      257       4  978300760
24       1     2728       4  978302039
25       1     3117       4  978300019
26       1     1022       5  978301753
27       1     2225       4  978824291
28       1      655       3  978302109
29       1     1526       4  978824330
30       1     2271       3  978300103
31       1     1250       5  978300055
32       1     1959       5  978301619
33       1      148       5  978301777
34       1     2849       4  978302124
35       1     2329       4  978302281
36       1     1016       5  978302205
37       1     2722       4  978302188
38       1      527       4  978302149
39       1      590       4  978302268
40       1        0       5  978824268
41       1     1768       5  978300172
42       1     1506       4  978824139
43       1     2286       5  978824291
44       1      907       4  978301368
45       1      773       4  978824291
46       1     1009       5  978300055
47       1     2252       3  978302205
48       1     3339       4  978300275
49       1     1838       4  978824330
50       1     1015       5  978301777
51       1     3045       4  978302174
52       1     3036       5  978301713

                                                title  \
0              One Flew Over the Cuckoo's Nest (1975)
1                                   Pocahontas (1995)
2                                         Gigi (1958)
3                        To Kill a Mockingbird (1962)
4                                      Titanic (1997)
5                             Sixth Sense, The (1999)
6                                       Tarzan (1999)
7                    Run Lola Run (Lola rennt) (1998)
8   Wallace & Gromit: The Best of Aardman Animatio...
9                               Close Shave, A (1995)
10                        Beauty and the Beast (1991)
11                                    Rain Man (1988)
12                            Schindler's List (1993)
13                  E.T. the Extra-Terrestrial (1982)
14                          Christmas Story, A (1983)
15                                       Bambi (1942)
16                                       Fargo (1996)
17                          Driving Miss Daisy (1989)
18                                     Ben-Hur (1959)
19                                     Aladdin (1992)
20                          Dead Poets Society (1989)
21                                My Fair Lady (1964)
22                         Princess Bride, The (1987)
23          Star Wars: Episode IV - A New Hope (1977)
24                                         Big (1988)
25                           Girl, Interrupted (1999)
26                         Sound of Music, The (1965)
27                                        Antz (1998)
28                   James and the Giant Peach (1996)
29                                    Hercules (1997)
30                              Meet Joe Black (1998)
31                          Back to the Future (1985)
32                         Saving Private Ryan (1998)
33                                   Apollo 13 (1995)
34                    Ferris Bueller's Day Off (1986)
35                      Miracle on 34th Street (1947)
36                                       Dumbo (1941)
37                                   Airplane! (1980)
38                          Secret Garden, The (1993)
39             Snow White and the Seven Dwarfs (1937)
40                                   Toy Story (1995)
41                     Last Days of Disco, The (1998)
42                                     Ponette (1996)
43                               Bug's Life, A (1998)
44                           Wizard of Oz, The (1939)
45                Hunchback of Notre Dame, The (1996)
46                                  Cinderella (1950)
47                               Pleasantville (1998)
48                             Erin Brockovich (2000)
49                                       Mulan (1998)
50                                Mary Poppins (1964)
51                                 Toy Story 2 (1999)
52                                  Awakenings (1990)

                                           genres
0                                           Drama
1            Animation|Children's|Musical|Romance
2                                         Musical
3                                           Drama
4                                   Drama|Romance
5                                        Thriller
6                            Animation|Children's
7                            Action|Crime|Romance
8                                       Animation
9                       Animation|Comedy|Thriller
10                   Animation|Children's|Musical
11                                          Drama
12                                      Drama|War
13                Children's|Drama|Fantasy|Sci-Fi
14                                   Comedy|Drama
15                           Animation|Children's
16                           Crime|Drama|Thriller
17                                          Drama
18                         Action|Adventure|Drama
19            Animation|Children's|Comedy|Musical
20                                          Drama
21                                Musical|Romance
22                Action|Adventure|Comedy|Romance
23                Action|Adventure|Fantasy|Sci-Fi
24                                 Comedy|Fantasy
25                                          Drama
26                                        Musical
27                           Animation|Children's
28                   Animation|Children's|Musical
29  Adventure|Animation|Children's|Comedy|Musical
30                                        Romance
31                                  Comedy|Sci-Fi
32                               Action|Drama|War
33                                          Drama
34                                         Comedy
35                                          Drama
36                   Animation|Children's|Musical
37                                         Comedy
38                               Children's|Drama
39                   Animation|Children's|Musical
40                    Animation|Children's|Comedy
41                                          Drama
42                                          Drama
43                    Animation|Children's|Comedy
44             Adventure|Children's|Drama|Musical
45                   Animation|Children's|Musical
46                   Animation|Children's|Musical
47                                         Comedy
48                                          Drama
49                           Animation|Children's
50                      Children's|Comedy|Musical
51                    Animation|Children's|Comedy
52                                          Drama